version: '3.7'

services:

  web:
    image: "dw-blog-django:dev"
    build:
      target: development_build
      context: .
      args:
        ENVIRONMENT: DEVELOPMENT
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgresdb
    volumes:
      - .:/code

  postgresdb:
    image: postgres:14.3-bullseye
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgresdb:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

volumes:
  postgresdb:
    driver: local
