# Generated by Django 4.1.3 on 2024-03-30 10:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("episode_number", models.IntegerField(editable=False)),
                ("title", models.CharField(max_length=300)),
                ("subtitle", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("author", "Author"),
                            ("admin", "Admin"),
                            ("translation", "Translation"),
                        ],
                        default="author",
                        max_length=20,
                    ),
                ),
                ("wykop_link", models.URLField()),
                ("podcast_link", models.URLField(blank=True, null=True)),
                (
                    "series",
                    models.CharField(
                        choices=[
                            ("main", "Main"),
                            ("ancient_christianity", "Ancient Christianity"),
                            ("islamic_history", "Islamic History"),
                            ("orthodox_christainity", "Orthodox Christianity"),
                            ("reformation", "Reformation"),
                            ("non_european_christianity", "Non-European Christianity"),
                        ],
                        default="main",
                        max_length=200,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-episode_number", "-created_at"),
            },
        ),
    ]
