# Generated by Django 4.1.3 on 2024-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
