# Generated by Django 4.1.3 on 2024-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="episode_number",
            field=models.IntegerField(),
        ),
    ]
